### ISSUE TITLE
Params

### ISSUE THREAD

**Issue by xentek** [hyperdriven/hyperdrive#3]
- [x] (#41) Params should be parsed in this order, with each subsequent source overwriting the previous value:
  - QueryString
  - Body (depends on content-type)
  - Path (e.g. `/resources/{id}`)
- [x] (#43) Params should be discrete types, and have a Name and Description, to promote re-use.
- [x] (#42) Params should be Optional or Required.
  - Params not allowed for a given request, should be dropped.
  - Required Params not present in request should cause a `400 Bad Input` error to be returned.
- [x] (#44) Params should be associated with a given `Endpoint`
  - Params should be method aware (as rules for optional/required, etc may differ between request methods)
  - Some Params, especially with `GET` requests may not be a part of a resource, but act as controls or filters for the requested data (e.g. search, date ranges, etc)

**Comment by xentek** [comment]
This may prove useful for params parsing and binding to structs: https://github.com/mholt/binding

**Comment by xentek** [comment]
Reorganized this ticket into several tickets so each part could be tackled independently, more or less. Will mark as done on the [project](https://github.com/hyperdriven/hyperdrive/projects/1) but keep this issue open until the sub-tickets are all addressed.

**Comment by xentek** [comment]
Moved deserialization to #53, and punting on it until [v0.0.6](https://github.com/hyperdriven/hyperdrive/milestone/5)
